name: taisei-build-tests
on:
  push:
    branches:
      - master
      - v1.*
    tags:
      - v1.*
    paths:
      - "**.c"
      - "**.h"
      - "**.yml"
      - "**.yaml"
      - "**.build"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.yml"
      - "**.yaml"
      - "**.build"

jobs:
  linux-test-build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Build Tools (apt)
      run: |
        sudo apt update
        sudo apt install -y -qq \
        build-essential \
        libsdl2-dev \
        libogg-dev \
        libopusfile-dev \
        libpng-dev \
        libzip-dev \
        libx11-dev \
        libwayland-dev \
        python3-docutils \
        libwebp-dev \
        libfreetype6-dev \
        libzstd-dev
        # pip
        pip install \
        meson==0.55.3 \
        ninja \
        zstandard

    # TODO: turn -Dwerror back on when build is fixed
    - name: Configure (Meson)
      run: |
        meson setup build/ \
          --verbose \
          --prefix=$(pwd)/build-test \
          --native-file scripts/ci/linux-x86_64-build-test-ci.ini

    - name: Build & Install
      run: |
        meson compile -C build/ --verbose
        meson install -C build/ --verbose

    - name: Run Test
      run: $(pwd)/build-test/bin/taisei -R $(pwd)/misc/tests/test-replay.tsr
      env:
        TAISEI_NOPRELOAD: 0
        TAISEI_PRELOAD_REQUIRED: 1

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_linux_fail.log
        path: build/meson-logs/meson-log.txt
        if-no-files-found: warn

  macos-test-build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: macos-10.15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set Up Build Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Build Tools
      run: |
        brew install \
        gcc \
        pkg-config \
        docutils \
        pygments \
        freetype2 \
        libzip \
        opusfile \
        libvorbis \
        webp \
        sdl2 \
        ninja
        # pip
        pip install \
        meson==0.55.3 \
        ninja \
        zstandard

    - name: Configure (Meson)
      run: |
        meson setup build/ \
        --verbose \
        --native-file scripts/ci/macos-x86_64-build-test-ci.ini \
        --prefix=$(pwd)/build-test

    - name: Build & Install
      run: |
        meson compile -C build/ --verbose
        meson install -C build/ --verbose

    - name: Run Test
      run: $(pwd)/build-test/Taisei.app/Contents/MacOS/Taisei -R $(pwd)/misc/tests/test-replay.tsr
      env:
        TAISEI_NOPRELOAD: 0
        TAISEI_PRELOAD_REQUIRED: 1

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_macos_fail.log
        path: build/meson-logs/meson-log.txt
        if-no-files-found: warn

  windows-test-build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    container: mstorsjo/llvm-mingw:20210423 # cross-compiler with mingw
    steps:
    - name: Install tools (Apt)
      run: |
        apt update
        apt install -y -qq software-properties-common
        add-apt-repository ppa:git-core/ppa -y
        apt install -y -qq \
        python3-docutils \
        python3-pip \
        git \
        nsis
        # pip
        pip3 install \
        meson==0.55.3 \
        ninja \
        zstandard

    - name: Checkout Code (Git)
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure Taisei (Meson)
      run: |
        meson setup build/ \
          --verbose \
          --prefix=$(pwd)/build-test \
          --cross-file scripts/ci/windows-llvm_mingw-x86_64-build-test-ci.ini

    - name: Build & Install
      run: |
        meson compile -C build/ --verbose
        meson install -C build/ --verbose

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_windows_fail.log
        path: build/meson-logs/meson-log.txt
        if-no-files-found: warn
