name: taisei-build-test

on:
  push:
    paths:
      - "**.c"
      - "**.h"
  pull_request:
    paths:
      - "**.h"
      - "**.h"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: apt install meson cmake build-essential libsdl2-dev libsdl2-mixer-dev libogg-dev libopusfile-dev libpng-dev libzip-dev libx11-dev libwayland-dev
    - run: git submodule update --init --recursive
    - run: mkdir build
    - run: cd build && meson configure -Dinstall_relative=true -Dbuildtype=debug -Db_ndebug=false -Db_lto=false -Dstrip=false -Ddeveloper=true && ninja

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install gcc meson cmake pkg-config docutils imagemagick pygments freetype2 libzip opusfile libvorbis webp sdl2 ninja
    - run: git submodule update --init --recursive
    - run: mkdir build
    - run: cd build && meson configure -Dinstall_relative=true -Dbuildtype=debug -Db_ndebug=false -Db_lto=false -Dstrip=false -Ddeveloper=true && ninja

