name: Publish Builds

# manual run only for publishing
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "Release tag to publish. (i.e: v1.4, v1.4.1, etc)"
        default: "vx.y.z"
      draftRelease:
        description: "Is this a 'draft'/'*-beta' release? (MUST ANSWER EITHER 'true' OR 'false' AS STRING INPUT)"
        required: true
        default: "false"
      preRelease:
        description: "Is this a 'prerelease'/'*-rc'? (MUST ANSWER EITHER 'true' OR 'false' AS STRING INPUT)"
        required: true
        default: "false"
    tags:
      - v[0-9].[0-9]**
      - v[0-9].[0-9]**-**

jobs:
  taisei-release:
    name: Release Actions
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Set Env Vars
        run: |
          echo "taisei_version=$(echo '${{ github.event.inputs.tag }}' | sed 's/^v//g')" >> $GITHUB_ENV
          mkdir releases/

      - name: Download Taisei Release Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          workflow_conclusion: success
          path: releases/

      - name: Create New Release
        uses: ncipollo/release-action@v1
        with:
          draft: ${{ github.event.inputs.draftRelease }}
          prerelease: ${{ github.event.inputs.preRelease }}
          artifacts: "releases/*${{ env.taisei_version }}*/*${{ env.taisei_version }}*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "refs/tags/v${{ env.taisei_version }}"

      # TODO: needs EMSCRIPTEN_RELEASE_DEPLOY_KEY as a project secret to publish to website repo
      # - name: Untar Emscripten
      #   run: >
      #     tar -xpf /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32.tar.xz
      #     -C /opt/emscripten-wasm32-${{ env.taisei_version }}-txz

      # - name: Deploy to GitHub Pages (Stable)
      #   uses: JamesIves/github-pages-deploy-action@releases/v4
      #   continue-on-error: true
      #   with:
      #     branch: live
      #     target-folder: ./play/stable/
      #     folder: /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32
      #     repository-name: taisei-project/taisei-website-new
      #     commit-message: "${{ github.repository }}@${{ github.sha }} - publishing stable build ${{ env.taisei_version }}"
      #     ssh-key: ${{ secrets.EMSCRIPTEN_RELEASE_DEPLOY_KEY }}
