name: "Release Builds"
on:
  push:
    branches:
      - v[0-9].[0-9]**
    tags:
      - v[0-9].[0-9]**
      - v[0-9].[0-9]**-**

env:
  MESON_VERSION: '0.56.2'
  EM_VERSION: '2.0.21'
  EM_CACHE_FOLDER: 'emsdk'
  TAISEI_NOPRELOAD: 0
  TAISEI_PRELOAD_REQUIRED: 1

jobs:
  linux-release-build:
    name: "Linux (x64/Source)"
    runs-on: ubuntu-18.04
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Tools
      run: >
        sudo apt update || true # debian cache is not atomic and can sometimes fail

        sudo apt install -y -qq
        build-essential
        libsdl2-dev
        libx11-dev
        libwayland-dev
        python3-docutils
        gnupg

        pip install
        meson==${{ env.MESON_VERSION }}
        ninja
        zstandard
        python-gnupg

    # NOTE: confusingly, 'fetch-depth: 0' == "get all history", not "no history"
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 1

    - name: Import GPG Key
      uses: taisei-project/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set Build Env
      id: vars
      run: |
        git fetch --force --tags # see: https://github.com/actions/checkout/issues/290
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

    - name: Configure
      run: >
        meson setup build/linux
        --native-file misc/ci/linux-x86_64-build-release.ini
        --prefix=$(pwd)/build-release

    - name: Build
      run: |
        meson compile -C build/linux --verbose
        meson install -C build/linux

    - name: Run Test
      run: $(pwd)/build-release/bin/taisei -R $(pwd)/misc/ci/tests/test-replay.tsr
      env:
        TAISEI_NOPRELOAD: ${{ env.TAISEI_NOPRELOAD }}
        TAISEI_PRELOAD_REQUIRED: ${{ env.TAISEI_PRELOAD_REQUIRED }}

    - name: Package (Binary)
      run: ninja txz -C build/linux --verbose

    - name: Upload Artifact (Binary)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: linux-x86_64-${{ steps.vars.outputs.tag }}-txz
        path: build/linux/Taisei-${{ steps.vars.outputs.tag }}-linux-x86_64.tar.xz*
        if-no-files-found: error

    - name: Package (Source)
      run: >
        meson rewrite kwargs set project / version v${{ steps.vars.outputs.tag }}

        meson --reconfigure build/linux

        meson dist -C build/linux --no-tests # disable test build, since we already know it compiles

        sha256sum build/linux/meson-dist/taisei-v${{ steps.vars.outputs.tag }}.tar.xz
        > build/linux/meson-dist/taisei-v${{ steps.vars.outputs.tag }}.tar.xz.sha256sum

        gpg --output build/linux/meson-dist/taisei-v${{ steps.vars.outputs.tag }}.tar.xz.sig
        --detach-sig build/linux/meson-dist/taisei-v${{ steps.vars.outputs.tag }}.tar.xz

    - name: Upload Artifact (Source)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: source-${{ steps.vars.outputs.tag }}-txz
        path: build/linux/meson-dist/taisei-v${{ steps.vars.outputs.tag }}.tar.xz*
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_linux_release_log
        path: build/linux/meson-logs/meson-log.txt
        if-no-files-found: warn

  macos-x64-release-build:
    name: macOS (x64)
    runs-on: macos-10.15
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Tools
      run: >
        brew install
        gcc
        pkg-config
        docutils
        pygments
        create-dmg
        gnupg

        pip install
        meson==${{ env.MESON_VERSION }}
        ninja
        zstandard
        python-gnupg

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: Import GPG Key
      uses: taisei-project/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set Build Env
      id: vars
      run: |
        git fetch --force --tags
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

    - name: Configure
      run: >
        meson setup build/macos
        --native-file misc/ci/macos-x86_64-build-release.ini
        --prefix=$(pwd)/build-release

    - name: Build
      run: |
        meson compile -C build/macos --verbose
        meson install -C build/macos

    - name: Run Test
      run: $(pwd)/build-release/Taisei.app/Contents/MacOS/Taisei -R $(pwd)/misc/ci/tests/test-replay.tsr
      env:
        TAISEI_NOPRELOAD: ${{ env.TAISEI_NOPRELOAD }}
        TAISEI_PRELOAD_REQUIRED: ${{ env.TAISEI_PRELOAD_REQUIRED }}

    - name: Package
      run: ninja dmg -C build/macos --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: macos-x86_64-${{ steps.vars.outputs.tag }}-dmg
        path: build/macos/Taisei-${{ steps.vars.outputs.tag }}-macOS-x86_64.dmg*
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_macos_intel_release_log
        path: build/macos/meson-logs/meson-log.txt
        if-no-files-found: warn

  macos-release-build-arm64:
    name: macOS (ARM64)
    runs-on: macos-10.15
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Tools
      run: >
        brew install
        gcc
        pkg-config
        docutils
        pygments
        create-dmg
        gnupg

        pip install
        meson==${{ env.MESON_VERSION }}
        ninja
        zstandard
        python-gnupg

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: Import GPG Key
      uses: taisei-project/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set Build Env
      id: vars
      run: |
        git fetch --force --tags
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
        echo "SDKROOT=$(xcrun --show-sdk-path --sdk macosx11.1)" >> $GITHUB_ENV # workaround for Xcode SDK path issue on GH runners

    - name: Configure
      run: >
        meson setup build/macos
        --cross-file misc/ci/macos-aarch64-build-release.ini
        --prefix=$(pwd)/build-release

    - name: Build
      run: |
        meson compile -C build/macos --verbose
        meson install -C build/macos

    - name: Package
      run: ninja dmg -C build/macos --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: macos-aarch64-${{ steps.vars.outputs.tag }}-dmg
        path: build/macos/Taisei-${{ steps.vars.outputs.tag }}-macOS-aarch64.dmg*
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_macos_arm64_release_log
        path: build/macos/meson-logs/meson-log.txt
        if-no-files-found: warn

  windows-release-build-x64:
    name: Windows (x64)
    runs-on: ubuntu-20.04
    container: mstorsjo/llvm-mingw:20210423 # cross-compiler with mingw
    steps:
    - name: Install Tools
      run: >
        apt update || true

        apt install -y -qq software-properties-common

        add-apt-repository ppa:git-core/ppa -y

        apt install -y -qq
        python3-docutils
        python3-pip
        git
        wget
        nsis
        gnupg

        pip3 install
        meson==${{ env.MESON_VERSION }}
        ninja
        zstandard
        python-gnupg

    # install NSIS 3.x manually/forcefully as it is not available for Ubuntu <20.04
    - name: Install NSIS 3.x
      run: >
        wget
        http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis-pluginapi_3.05-2_all.deb
        http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis-common_3.05-2_all.deb
        http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis_3.05-2_amd64.deb
        -P /tmp

        dpkg -i --force-all
        /tmp/nsis-common_3.05-2_all.deb
        /tmp/nsis_3.05-2_amd64.deb
        /tmp/nsis-pluginapi_3.05-2_all.deb

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: Checkout ANGLE DLLs
      uses: actions/checkout@v2
      with:
        repository: taisei-project/angle-compiled
        path: angle-compiled

    - name: Import GPG Key
      uses: taisei-project/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set Build Env
      id: vars
      run: >
        git fetch --force --tags

        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

        sed -i
        -e "s+libegl_path = ''+libegl_path = \'$(pwd)/angle-compiled/dll/x64/libEGL.dll\'+g"
        -e "s+libgles_path = ''+libgles_path = '$(pwd)/angle-compiled/dll/x64/libGLESv2.dll'+g"
        misc/ci/windows-llvm_mingw-x86_64-build-release.ini

        echo "Windows (x64) Release Machine File:"

        cat misc/ci/windows-llvm_mingw-x86_64-build-release.ini

    - name: Configure
      run: >
        meson setup build/windows
        --cross-file misc/ci/windows-llvm_mingw-x86_64-build-release.ini
        --prefix=$(pwd)/build-release

    - name: Build
      run: meson compile -C build/windows

    - name: Package (EXE)
      run: ninja nsis -C build/windows --verbose

    - name: Upload Artifact (EXE)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-x86_64-${{ steps.vars.outputs.tag }}-setup-exe
        path: build/windows/Taisei-${{ steps.vars.outputs.tag }}-setup-x86_64.exe*
        if-no-files-found: error

    - name: Package (ZIP)
      run: ninja zip -C build/windows --verbose

    - name: Upload Artifact (ZIP)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-x86_64-${{ steps.vars.outputs.tag }}-zip
        path: build/windows/Taisei-${{ steps.vars.outputs.tag }}-windows-x86_64.zip*
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_windows_x64_release_log
        path: build/windows/meson-logs/meson-log.txt
        if-no-files-found: warn

  windows-release-build-x86:
    name: Windows (x86)
    runs-on: ubuntu-20.04
    container: mstorsjo/llvm-mingw:20210423 # cross-compiler with mingw
    steps:
    - name: Install Tools
      run: >
        apt update || true

        apt install -y -qq software-properties-common

        add-apt-repository ppa:git-core/ppa -y

        apt install -y -qq
        python3-docutils
        python3-pip
        git
        wget
        nsis
        gnupg

        pip3 install
        meson==${{ env.MESON_VERSION }}
        ninja
        zstandard
        python-gnupg

    # install NSIS 3.x manually/forcefully as it is not available for Ubuntu <20.04
    - name: Install NSIS 3.x
      run: >
        wget
        http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis-pluginapi_3.05-2_all.deb
        http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis-common_3.05-2_all.deb
        http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis_3.05-2_amd64.deb
        -P /tmp

        dpkg -i --force-all
        /tmp/nsis-common_3.05-2_all.deb
        /tmp/nsis_3.05-2_amd64.deb
        /tmp/nsis-pluginapi_3.05-2_all.deb

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: Checkout ANGLE DLLs
      uses: actions/checkout@v2
      with:
        repository: taisei-project/angle-compiled
        path: angle-compiled

    - name: Import GPG Key
      uses: taisei-project/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set Build Env
      id: vars
      run: >
        git fetch --force --tags

        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

        sed -i
        -e "s+libegl_path = ''+libegl_path = '$(pwd)/angle-compiled/dll/x86/libEGL.dll'+g"
        -e "s+libgles_path = ''+libgles_path = '$(pwd)/angle-compiled/dll/x86/libGLESv2.dll'+g"
        misc/ci/windows-llvm_mingw-x86-build-release.ini

        echo "Windows (x86) Release Machine File:"

        cat misc/ci/windows-llvm_mingw-x86-build-release.ini

    - name: Configure
      run: >
        meson setup build/windows
        --cross-file misc/ci/windows-llvm_mingw-x86-build-release.ini
        --prefix=$(pwd)/build-release

    - name: Build
      run: meson compile -C build/windows

    - name: Package (EXE)
      run: ninja nsis -C build/windows --verbose

    - name: Upload Artifact (EXE)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-x86-${{ steps.vars.outputs.tag }}-setup-exe
        path: build/windows/Taisei-${{ steps.vars.outputs.tag }}-setup-x86.exe*
        if-no-files-found: error

    - name: Package (ZIP)
      run: ninja zip -C build/windows --verbose

    - name: Upload Artifact (ZIP)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-x86-${{ steps.vars.outputs.tag }}-zip
        path: build/windows/Taisei-${{ steps.vars.outputs.tag }}-windows-x86.zip*
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_windows_x86_release_log
        path: build/windows/meson-logs/meson-log.txt
        if-no-files-found: warn

  emscripten-release-build:
    name: Emscripten Release
    runs-on: ubuntu-20.04
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Tools
      run: >
        sudo apt update || true

        sudo apt install -y -qq
        python3-docutils
        python3-pip
        git
        gnupg

        pip install
        meson==${{ env.MESON_VERSION }}
        ninja
        zstandard
        python-gnupg

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 1

    - name: Import GPG Key
      uses: taisei-project/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set Build Env
      id: vars
      run: |
        git fetch --force --tags
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

    - name: Fetch Cached Emscripten SDK
      id: emsdk-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.EM_CACHE_FOLDER }}
        key: ${{ env.EM_VERSION }}-${{ runner.os }}

    - name: Install Emscripten SDK
      if: steps.emsdk-cache.outputs.cache-hit != 'true'
      run: |
        rm -rf ./${{ env.EM_CACHE_FOLDER }}/
        git clone https://github.com/emscripten-core/emsdk.git
        ${{ env.EM_CACHE_FOLDER }}/emsdk install ${{ env.EM_VERSION }}
        ${{ env.EM_CACHE_FOLDER }}/emsdk activate ${{ env.EM_VERSION }}

    - name: Verify Emscripten SDK
      run: >
        source ${{ env.EM_CACHE_FOLDER }}/emsdk_env.sh

        emcc -v

        sed -i
        "s+toolchain = ''+toolchain = '$(pwd)/${{ env.EM_CACHE_FOLDER }}/upstream/emscripten/'+g"
        misc/ci/emscripten-build.ini

        echo "Emscripten Release Machine File:"

        cat misc/ci/emscripten-build.ini

    - name: Configure
      run: >
        source ${{ env.EM_CACHE_FOLDER }}/emsdk_env.sh

        meson setup build/emscripten
        --cross-file misc/ci/emscripten-build.ini
        --prefix=$(pwd)/build-release
        -Drelease_files=true

        meson configure
        -Dbuild.cpp_std=gnu++14
        build/emscripten # set correct C++ version

    - name: Build
      run: |
        source ${{ env.EM_CACHE_FOLDER }}/emsdk_env.sh
        meson compile -C build/emscripten --verbose

    - name: Package
      run: |
        source ${{ env.EM_CACHE_FOLDER }}/emsdk_env.sh
        ninja txz -C build/emscripten --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: emscripten-wasm32-${{ steps.vars.outputs.tag }}-txz
        path: build/emscripten/Taisei-${{ steps.vars.outputs.tag }}-emscripten-wasm32.tar.xz*
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_emscripten_build_log
        path: build/emscripten/meson-logs/meson-log.txt
        if-no-files-found: warn

  switch-release-build:
    name: Switch (ARM64)
    runs-on: ubuntu-20.04
    container: taiseiproject/switch-toolkit:20210530
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 1

    - name: Import GPG Key
      uses: taisei-project/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set Build Env
      id: vars
      run: |
        git fetch --force --tags
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
        switch/crossfile.sh > misc/ci/switch-crossfile-ci.ini

    - name: Configure
      run: >
        meson setup build/nx
        --cross-file=misc/ci/switch-crossfile-ci.ini
        --prefix=$(pwd)/build-release
        -Drelease_files=true

    - name: Build
      run: meson compile -C build/nx --verbose

    - name: Package
      run: ninja zip -C build/nx --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: switch-aarch64-${{ steps.vars.outputs.tag }}-zip
        path: build/nx/Taisei-${{ steps.vars.outputs.tag }}-switch-aarch64.zip*
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_switch_release_log
        path: build/nx/meson-logs/meson-log.txt
        if-no-files-found: warn
